// Copyright 2025 promptLM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * Generates the OpenAPI-driven mock backend surface under
 * `src/generated/mock/`:
 *
 *   - `operation-index.ts`   metadata for every operation (opId, method, path,
 *                            path-param order, matcher regex) so the runtime
 *                            can route an incoming request to a handler
 *                            without re-parsing the spec.
 *   - `example-responses.ts` schema-driven default response bodies for every
 *                            (opId, statusCode) pair, used by handlers that
 *                            do not synthesise a body from `MockBackendState`.
 *   - `handlers.ts`          one typed handler per operation, referencing
 *                            `operations[opId]['requestBody'/'responses']`
 *                            from `@promptlm/api-client`. Handlers delegate to
 *                            hand-written `MockBackendState` methods so the
 *                            generated surface only carries wire-format
 *                            knowledge; behaviour lives in `src/mock/`.
 *
 * Determinism is load-bearing: regenerating the files twice in a row must
 * produce zero `git diff`. We achieve that by:
 *   1. iterating operations in spec order (preserved by JSON parse → object
 *      property iteration order in Node ≥ 12 for non-integer keys);
 *   2. sorting all `Object.entries` we emit;
 *   3. resolving `$ref` synchronously with cycle detection that returns a
 *      placeholder rather than recursing forever.
 */

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const workspaceRoot = path.resolve(__dirname, '..');
const specPath = path.resolve(
  workspaceRoot,
  '..',
  '..',
  'apps',
  'promptlm-webapp',
  'target',
  'generated',
  'openapi',
  'promptlm-webapp-openapi.json',
);
const outputDir = path.join(workspaceRoot, 'src', 'generated', 'mock');

const HTTP_METHODS = ['get', 'put', 'post', 'delete', 'patch', 'options', 'head'];

const LICENSE_HEADER = `// Copyright 2025 promptLM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/* generated by scripts/generate-mock.mjs — do not edit */
`;

/**
 * Operations whose default response body is synthesised from
 * `MockBackendState` at request time rather than from the static
 * `example-responses` table. The generator still emits a placeholder example
 * for these (so ajv validation has *something* to start from in unit tests
 * that bypass the state), but the runtime handler ignores it.
 *
 * Adding a new state-driven operation: add the opId here AND write the
 * corresponding helper on `MockBackendState`.
 */
const STATE_DRIVEN_HANDLERS = {
  getActiveProject: { kind: 'activeProject404' },
  cloneStore: { kind: 'cloneStore' },
  createStore: { kind: 'createStore' },
  switchProject: { kind: 'switchProject' },
  connectRepository: { kind: 'connectRepository' },
  listOwners: { kind: 'listOwners' },
  getAllProjects: { kind: 'allProjects' },
  getById: { kind: 'promptById' },
  updatePromptSpec: { kind: 'updatePromptSpec' },
  retirePrompt: { kind: 'retirePrompt' },
  listPromptSpecs: { kind: 'listPromptSpecs' },
  createPromptSpec: { kind: 'createPromptSpec' },
  releasePrompt: { kind: 'releasePrompt' },
  completeReleasePrompt: { kind: 'completeReleasePrompt' },
  executeStoredPrompt: { kind: 'executeStoredPrompt' },
  executePrompt: { kind: 'executePrompt' },
  getRepoHistory: { kind: 'repoHistory' },
  getRevisionsByGroupAndName: { kind: 'revisionsByGroupAndName' },
  getDefaultTemplate: { kind: 'defaultTemplate' },
  getPromptStats: { kind: 'promptStats' },
  getPromptGroups: { kind: 'promptGroups' },
  getCatalog: { kind: 'modelCatalog' },
  getCapabilities: { kind: 'capabilities' },
};

/**
 * Maps an OpenAPI path template (e.g. `/api/prompts/{id}/release`) to a
 * JS-source regex literal that captures each `{param}` as a named group, and
 * collects the parameter names in declaration order.
 *
 * Express-style colon syntax is intentionally avoided — Playwright route
 * matching strips the leading origin, so we match against `url.pathname`
 * directly.
 */
export function pathTemplateToMatcher(template) {
  const paramNames = [];
  // Anchored at both ends and escaped for regex specials except the brace
  // placeholders we expand below.
  const escaped = template.replace(/[.+*?^$()|[\]\\]/g, '\\$&');
  const pattern = escaped.replace(/\{([^}]+)\}/g, (_, name) => {
    paramNames.push(name);
    return '(?<' + name + '>[^/]+)';
  });
  return { pattern: '^' + pattern + '$', paramNames };
}

/**
 * Resolves `$ref` chains within a single OpenAPI spec. Returns the resolved
 * fragment, or the original `node` if it is not a ref. Cycles return the
 * partially-resolved object that was being walked (which yields an empty
 * `{}` example — acceptable for ajv defaults).
 */
function resolveRef(spec, node, seen = new Set()) {
  if (!node || typeof node !== 'object' || !('$ref' in node)) {
    return node;
  }
  const ref = node.$ref;
  if (typeof ref !== 'string' || !ref.startsWith('#/')) {
    return node;
  }
  if (seen.has(ref)) {
    return {};
  }
  seen.add(ref);
  const target = ref
    .slice(2)
    .split('/')
    .reduce((acc, key) => (acc && typeof acc === 'object' ? acc[key] : undefined), spec);
  if (!target) {
    return node;
  }
  return resolveRef(spec, target, seen);
}

/**
 * Returns a JSON-serializable default value for a JSON-Schema node. Order of
 * precedence (per design doc §1, "Example synthesis (3 tiers)"):
 *
 *   1. spec-provided `default` or `example` if present (and not the
 *      springdoc no-op `""`/`null`/`0`/`false`/`[]`/`{}` shape — those are
 *      stripped by `normalize-openapi.mjs` before this script runs, so any
 *      remaining default/example here is semantically meaningful);
 *   2. schema-driven defaults: `enum[0]`, then type-based zero values;
 *   3. for `oneOf`, the first listed alternative (design rule:
 *      "`ChatCompletionRequest` wins for `PromptSpec.request`" — first in
 *      oneOf declaration order).
 *
 * `additionalProperties: true` and free-form `JsonNode`-style schemas yield
 * `{}` rather than `null` so they are safe to pass through ajv.
 */
export function schemaDefault(spec, schema, seen = new Set()) {
  if (!schema || typeof schema !== 'object') {
    return null;
  }
  if (schema.$ref) {
    if (seen.has(schema.$ref)) {
      return {};
    }
    const nextSeen = new Set(seen);
    nextSeen.add(schema.$ref);
    const resolved = resolveRef(spec, schema, new Set());
    if (resolved === schema) {
      return {};
    }
    return schemaDefault(spec, resolved, nextSeen);
  }
  if (Object.prototype.hasOwnProperty.call(schema, 'default')) {
    return schema.default;
  }
  if (Object.prototype.hasOwnProperty.call(schema, 'example')) {
    return schema.example;
  }
  if (Array.isArray(schema.enum) && schema.enum.length > 0) {
    return schema.enum[0];
  }
  if (Array.isArray(schema.oneOf) && schema.oneOf.length > 0) {
    // Polymorphism rule: first member wins. Tests needing other branches
    // seed explicit values via state.
    return schemaDefault(spec, schema.oneOf[0], seen);
  }
  if (Array.isArray(schema.allOf) && schema.allOf.length > 0) {
    // Merge required properties from all branches.
    const merged = {};
    for (const branch of schema.allOf) {
      const resolved = resolveRef(spec, branch);
      const branchDefault = schemaDefault(spec, resolved, seen);
      if (branchDefault && typeof branchDefault === 'object' && !Array.isArray(branchDefault)) {
        Object.assign(merged, branchDefault);
      }
    }
    return merged;
  }
  if (Array.isArray(schema.anyOf) && schema.anyOf.length > 0) {
    return schemaDefault(spec, schema.anyOf[0], seen);
  }

  // Type-driven path.
  const type = Array.isArray(schema.type) ? schema.type.find((t) => t !== 'null') : schema.type;
  switch (type) {
    case 'string':
      if (schema.format === 'date-time') return '1970-01-01T00:00:00Z';
      if (schema.format === 'uuid') return '00000000-0000-0000-0000-000000000000';
      return '';
    case 'integer':
    case 'number':
      return 0;
    case 'boolean':
      return false;
    case 'array':
      return [];
    case 'object':
    case undefined: {
      const props = schema.properties ?? {};
      const required = Array.isArray(schema.required) ? schema.required : [];
      const out = {};
      // Required fields only, in spec declaration order.
      for (const key of Object.keys(props)) {
        if (!required.includes(key)) continue;
        out[key] = schemaDefault(spec, props[key], seen);
      }
      return out;
    }
    case 'null':
      return null;
    default:
      return null;
  }
}

/**
 * Extracts every (opId, method, path, response status, response schema) tuple
 * from the spec so the rest of the generator can iterate operations once.
 */
export function collectOperations(spec) {
  const operations = [];
  const paths = spec.paths ?? {};
  for (const [routePath, pathItem] of Object.entries(paths)) {
    if (!pathItem || typeof pathItem !== 'object') continue;
    for (const method of HTTP_METHODS) {
      const op = pathItem[method];
      if (!op || typeof op !== 'object') continue;
      const opId = op.operationId;
      if (typeof opId !== 'string' || opId.length === 0) {
        throw new Error(
          'Operation ' + method.toUpperCase() + ' ' + routePath + ' has no operationId',
        );
      }
      const requestBodyContent =
        op.requestBody &&
        op.requestBody.content &&
        op.requestBody.content['application/json'] &&
        op.requestBody.content['application/json'].schema;
      const responses = {};
      for (const [status, response] of Object.entries(op.responses ?? {})) {
        if (!response || typeof response !== 'object') continue;
        // Some operations declare `*/*` instead of `application/json`
        // (springdoc emits it when the controller method returns
        // `ResponseEntity<?>` without explicit produces). Use whichever
        // content type the spec lists.
        const content = response.content && (
          response.content['application/json'] ||
          response.content['*/*'] ||
          Object.values(response.content)[0]
        );
        const contentType = response.content
          ? (response.content['application/json']
              ? 'application/json'
              : (response.content['*/*'] ? '*/*' : Object.keys(response.content)[0]))
          : null;
        responses[status] = {
          description: typeof response.description === 'string' ? response.description : '',
          contentType,
          schema: content && content.schema ? content.schema : null,
        };
      }
      operations.push({
        opId,
        method: method.toUpperCase(),
        path: routePath,
        requestSchema: requestBodyContent || null,
        responses,
      });
    }
  }
  return operations;
}

/**
 * Picks the canonical "success" response status for an operation. Prefers
 * `200`, then any 2xx in ascending order, then `204`. Falls back to the first
 * declared status if no 2xx is present — defensive only; the spec always
 * declares a 2xx today.
 */
export function pickSuccessStatus(responses) {
  const statuses = Object.keys(responses);
  if (statuses.includes('200')) return '200';
  const twoXx = statuses
    .filter((s) => /^2\d\d$/.test(s))
    .sort((a, b) => Number(a) - Number(b));
  if (twoXx.length > 0) return twoXx[0];
  if (statuses.length > 0) return statuses[0];
  return '200';
}

/**
 * Stringifies an example with stable indentation. We use 2-space JSON; the
 * test asserts deep-equality on parsed values, so formatting only matters for
 * `git diff` ergonomics.
 */
function formatLiteral(value) {
  return JSON.stringify(value, null, 2);
}

/**
 * Emits `operation-index.ts` — a single array literal exposing the metadata
 * Playwright route handlers need to match a request to a handler:
 *
 *   - `opId`                  key into `defaultHandlers`
 *   - `method`                upper-case HTTP verb
 *   - `pathTemplate`          original OpenAPI path
 *   - `pathPattern`           anchored regex source matching `url.pathname`
 *   - `pathParamNames`        named groups in `pathPattern`, in order
 *   - `successStatus`         numeric success status the default handler emits
 */
export function renderOperationIndex(operations) {
  const entries = operations.map((op) => {
    const { pattern, paramNames } = pathTemplateToMatcher(op.path);
    const successStatus = pickSuccessStatus(op.responses);
    return (
      '  {\n' +
      '    opId: ' +
      JSON.stringify(op.opId) +
      ',\n' +
      '    method: ' +
      JSON.stringify(op.method) +
      ',\n' +
      '    pathTemplate: ' +
      JSON.stringify(op.path) +
      ',\n' +
      '    pathPattern: ' +
      JSON.stringify(pattern) +
      ',\n' +
      '    pathParamNames: ' +
      JSON.stringify(paramNames) +
      ',\n' +
      '    successStatus: ' +
      Number(successStatus) +
      ',\n' +
      '  }'
    );
  });
  return (
    LICENSE_HEADER +
    '\n' +
    'export interface OperationDescriptor {\n' +
    '  readonly opId: string;\n' +
    '  readonly method: string;\n' +
    '  readonly pathTemplate: string;\n' +
    '  readonly pathPattern: string;\n' +
    '  readonly pathParamNames: readonly string[];\n' +
    '  readonly successStatus: number;\n' +
    '}\n' +
    '\n' +
    'export const operationIndex: readonly OperationDescriptor[] = [\n' +
    entries.join(',\n') +
    ',\n' +
    '] as const;\n'
  );
}

/**
 * Emits `example-responses.ts` — a map keyed by `opId` whose value is a map
 * from status code to a schema-derived example body. Used as a fallback when
 * a handler does not produce a state-derived response.
 */
export function renderExampleResponses(spec, operations) {
  const lines = [LICENSE_HEADER + '\n', 'export const exampleResponses = {'];
  for (const op of operations) {
    const statusEntries = [];
    for (const [status, response] of Object.entries(op.responses).sort(([a], [b]) =>
      a.localeCompare(b),
    )) {
      if (!response.schema) {
        // No JSON body declared — model as `undefined` so consumers can
        // distinguish "no content" from "empty body".
        statusEntries.push('    ' + JSON.stringify(status) + ': undefined');
        continue;
      }
      const example = schemaDefault(spec, response.schema);
      statusEntries.push(
        '    ' +
          JSON.stringify(status) +
          ': ' +
          formatLiteral(example).replace(/\n/g, '\n    '),
      );
    }
    lines.push('  ' + JSON.stringify(op.opId) + ': {');
    lines.push(statusEntries.join(',\n'));
    lines.push('  },');
  }
  lines.push('} as const;');
  lines.push('');
  lines.push('export type ExampleResponses = typeof exampleResponses;');
  lines.push('');
  return lines.join('\n');
}

/**
 * Emits `handlers.ts`.
 *
 * Every operation gets a handler typed against
 * `operations[opId]['requestBody'/'responses']`. By default each handler
 * delegates to a `MockBackendState.handle<HandlerKind>(...)` method on the
 * hand-written state object. State-driven kinds are listed in
 * `STATE_DRIVEN_HANDLERS` above; an operation not in that table falls back to
 * returning the canonical success example from `exampleResponses`.
 *
 * The dispatch table `defaultHandlers` is exported as `as const` and asserted
 * by `scripts/generate-mock.test.mjs` to cover the operationId list exactly —
 * that's the drift guardrail at the handler-table layer.
 */
export function renderHandlers(operations) {
  const importNames = new Set(['MockBackendState']);
  const handlerEntries = [];
  const handlerDecls = [];

  for (const op of operations) {
    const stateBinding = STATE_DRIVEN_HANDLERS[op.opId];
    // openapi-typescript marks request bodies as `requestBody?:` (optional)
    // on operations whose Java controller declares the body parameter as
    // not `@RequestBody(required = true)`. Wrap in NonNullable so the
    // typed handler signature can index into `.content` regardless.
    const reqType =
      op.requestSchema != null
        ? "NonNullable<operations['" + op.opId + "']['requestBody']>['content']['application/json']"
        : 'undefined';
    // Use the canonical success status response type. Resolve the content
    // type the spec actually declared for this status (most operations use
    // `application/json`, a handful use `*/*`).
    const successStatus = pickSuccessStatus(op.responses);
    const successContentType = op.responses[successStatus]?.contentType;
    const resType = successContentType
      ? ("operations['" +
        op.opId +
        "']['responses'][" +
        JSON.stringify(successStatus) +
        "]['content'][" +
        JSON.stringify(successContentType) +
        ']')
      : 'undefined';

    const handlerName = op.opId + '_default';
    handlerDecls.push(
      '/**\n' +
        ' * ' +
        op.method +
        ' ' +
        op.path +
        '\n' +
        ' *\n' +
        ' * Default handler' +
        (stateBinding
          ? ' — delegates to state.handle' + capitalize(stateBinding.kind) + '().'
          : ' — returns the schema-derived example for status ' + successStatus + '.') +
        '\n' +
        ' */\n' +
        'export const ' +
        handlerName +
        ': MockHandler<\n' +
        '  ' +
        reqType +
        ',\n' +
        '  ' +
        resType +
        '\n' +
        '> = (args) => {\n' +
        (stateBinding
          ? '  return args.state.handle' + capitalize(stateBinding.kind) + '(args) as MockResponse<\n' +
            '    ' +
            resType +
            '\n  >;\n'
          : '  return {\n' +
            '    status: ' +
            Number(successStatus) +
            ',\n' +
            '    body: exampleResponses[' +
            JSON.stringify(op.opId) +
            '][' +
            JSON.stringify(successStatus) +
            "] as " +
            resType +
            ',\n' +
            '  };\n') +
        '};',
    );
    handlerEntries.push('  ' + op.opId + ': ' + handlerName);
  }

  const body =
    LICENSE_HEADER +
    '\n' +
    "import type { operations } from '../openapi';\n" +
    "import type { MockBackendState } from '../../mock/state';\n" +
    "import type { MockHandler, MockResponse } from '../../mock/handler-types';\n" +
    "import { exampleResponses } from './example-responses';\n" +
    '\n' +
    handlerDecls.join('\n\n') +
    '\n\n' +
    'export const defaultHandlers = {\n' +
    handlerEntries.join(',\n') +
    ',\n' +
    '} as const;\n' +
    '\n' +
    'export type DefaultHandlers = typeof defaultHandlers;\n' +
    '\n' +
    '// Silence "unused" warning when no state-driven handler is generated.\n' +
    'export type _StateRef = MockBackendState;\n';
  return body;
}

function capitalize(s) {
  if (!s) return s;
  return s.charAt(0).toUpperCase() + s.slice(1);
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === __filename;

if (isMain) {
  let raw;
  try {
    raw = await readFile(specPath, 'utf8');
  } catch (err) {
    if (err && err.code === 'ENOENT') {
      console.error('Error: OpenAPI spec not found at ' + specPath + '.');
      console.error(
        'Run `./mvnw -pl apps/promptlm-webapp -am install -DskipTests` from the repo root to generate it first.',
      );
      process.exit(1);
    }
    throw err;
  }
  const spec = JSON.parse(raw);
  const operations = collectOperations(spec);
  operations.sort((a, b) => a.opId.localeCompare(b.opId));

  await mkdir(outputDir, { recursive: true });
  await writeFile(path.join(outputDir, 'operation-index.ts'), renderOperationIndex(operations));
  await writeFile(path.join(outputDir, 'example-responses.ts'), renderExampleResponses(spec, operations));
  await writeFile(path.join(outputDir, 'handlers.ts'), renderHandlers(operations));

  console.log('Generated mock surface for ' + operations.length + ' operations under ' + path.relative(workspaceRoot, outputDir));
}
