// Copyright 2025 promptLM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import { useMemo, useState } from 'react';
import {
  ActivityHeatmap,
  AuthorsTable,
  ChangeTimeline,
  DiffPickerStrip,
  DiffSummary,
  DocumentChrome,
  GroupBlocks,
  LatestCommitCard,
  ModelMatrix,
  Mono,
  PartHeader,
  PlaceholderIndex,
  ReportSection,
  SpecDiffBody,
  type DiffSelection,
  type GroupCatalogItem,
  type TimelineEntry,
} from '@promptlm/ui';
import { loadSpecs, type ReportSpecs } from './specs';
import { buildDiffHref, buildPromptHref, useHashRoute } from './router';

const RootBackground: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <div
    className="pl"
    style={{
      background: 'var(--pl-canvas)',
      fontFamily: 'var(--pl-display)',
      color: 'var(--pl-ink-900)',
      minHeight: '100vh',
    }}
  >
    {children}
  </div>
);

const TitleBlock: React.FC<{ specs: ReportSpecs }> = ({ specs }) => (
  <div style={{ padding: '48px 56px 24px' }}>
    <Mono
      size={11}
      color="var(--pl-ink-500)"
      style={{ letterSpacing: '0.14em', textTransform: 'uppercase', marginBottom: 14, display: 'block' }}
    >
      Repository report
    </Mono>
    <h1
      style={{
        margin: 0,
        fontFamily: 'var(--pl-display)',
        fontSize: 46,
        fontWeight: 500,
        letterSpacing: '-0.02em',
        lineHeight: 1.05,
        color: 'var(--pl-ink-900)',
        maxWidth: 880,
      }}
    >
      What's in this repo,
      <span style={{ color: 'var(--pl-ink-500)' }}> and how it got that way.</span>
    </h1>
    <p
      style={{
        margin: '18px 0 0',
        fontSize: 16,
        lineHeight: 1.55,
        color: 'var(--pl-ink-600)',
        maxWidth: 720,
      }}
    >
      A standing view of <Mono color="var(--pl-ink-700)">prompts/**.toml</Mono>: every prompt at
      HEAD, every change that brought it here. Generated from spec files alone — no runtime, no
      telemetry.
    </p>
    <LatestCommitCard commit={specs.latestCommit} />
  </div>
);

const ReportFooter: React.FC<{ specs: ReportSpecs }> = ({ specs }) => (
  <div
    style={{
      padding: '20px 56px',
      borderTop: '1px solid var(--pl-ink-200)',
      background: 'var(--pl-paper)',
      display: 'flex',
      alignItems: 'center',
      gap: 16,
    }}
  >
    <Mono size={11} color="var(--pl-ink-500)">
      generated by <span style={{ color: 'var(--pl-ink-800)' }}>{specs.generatedBy}</span>
    </Mono>
    <span style={{ width: 1, height: 12, background: 'var(--pl-ink-300)' }} />
    <Mono size={11} color="var(--pl-ink-500)">
      source <span style={{ color: 'var(--pl-ink-800)' }}>{specs.repo.url} · {specs.repo.defaultBranch} · {specs.latestCommit.sha}</span>
    </Mono>
    <div style={{ flex: 1 }} />
    <Mono size={11} color="var(--pl-ink-500)">host: github pages · static</Mono>
  </div>
);

const OverviewPage: React.FC<{
  specs: ReportSpecs;
  onPromptSelect: (item: GroupCatalogItem) => void;
  onTimelineDiff: (entry: TimelineEntry) => void;
}> = ({ specs, onPromptSelect, onTimelineDiff }) => (
  <RootBackground>
    <DocumentChrome
      source={`promptlm report · ${specs.repo.url}`}
      detail={`${specs.repo.defaultBranch} · ${specs.latestCommit.sha}`}
    />
    <TitleBlock specs={specs} />

    <PartHeader letter="A" title="History" sub="Every change to the corpus, newest first." />

    <ReportSection num="01" title="Activity" anchor="activity">
      <p
        style={{
          margin: '0 0 20px',
          fontSize: 14,
          lineHeight: 1.6,
          color: 'var(--pl-ink-700)',
          maxWidth: 720,
        }}
      >
        Commits to <Mono color="var(--pl-ink-900)">prompts/</Mono> over the last 90 days.
      </p>
      <ActivityHeatmap
        data={specs.activity.cells}
        weeks={specs.activity.weeks}
        days={specs.activity.days}
        monthLabels={specs.activity.monthLabels}
        totalLabel={`${specs.activity.total} commits · last 90 days`}
      />
    </ReportSection>

    <ReportSection num="02" title="Timeline" anchor="timeline">
      <p
        style={{
          margin: '0 0 20px',
          fontSize: 14,
          lineHeight: 1.6,
          color: 'var(--pl-ink-700)',
          maxWidth: 720,
        }}
      >
        Spec-level changes: a prompt was added, a field was changed, a placeholder appeared.
        Diffs are computed at the <Mono color="var(--pl-ink-900)">PromptSpec</Mono> level, not
        the raw file — so renaming a key shows up as a key change, not twelve line moves.
      </p>
      <ChangeTimeline entries={specs.timeline} onOpenDiff={onTimelineDiff} />
    </ReportSection>

    <ReportSection num="03" title="Authors" anchor="authors">
      <p
        style={{
          margin: '0 0 20px',
          fontSize: 14,
          lineHeight: 1.6,
          color: 'var(--pl-ink-700)',
          maxWidth: 720,
        }}
      >
        Everyone who has touched a spec. Counted from{' '}
        <Mono color="var(--pl-ink-900)">git log</Mono> across the entire history of{' '}
        <Mono color="var(--pl-ink-900)">prompts/</Mono>.
      </p>
      <AuthorsTable authors={specs.authors} />
    </ReportSection>

    <PartHeader letter="B" title="Catalog at HEAD" sub="The corpus as it stands right now." />

    <ReportSection num="04" title="By group" anchor="groups">
      <p
        style={{
          margin: '0 0 20px',
          fontSize: 14,
          lineHeight: 1.6,
          color: 'var(--pl-ink-700)',
          maxWidth: 720,
        }}
      >
        {specs.totalPrompts} prompts across {specs.groups.length} groups. Each row is a spec file
        in <Mono color="var(--pl-ink-900)">prompts/</Mono>.
      </p>
      <GroupBlocks groups={specs.groups} onSelect={onPromptSelect} />
    </ReportSection>

    <ReportSection num="05" title="Models in use" anchor="models">
      <p
        style={{
          margin: '0 0 20px',
          fontSize: 14,
          lineHeight: 1.6,
          color: 'var(--pl-ink-700)',
          maxWidth: 720,
        }}
      >
        Distinct <Mono color="var(--pl-ink-900)">request.model</Mono> values declared across all
        specs. A prompt counts once per model it pins.
      </p>
      <ModelMatrix models={specs.models} totalPrompts={specs.totalPrompts} />
    </ReportSection>

    <ReportSection num="06" title="Placeholder index" anchor="placeholders">
      <p
        style={{
          margin: '0 0 20px',
          fontSize: 14,
          lineHeight: 1.6,
          color: 'var(--pl-ink-700)',
          maxWidth: 720,
        }}
      >
        Every variable referenced by every prompt at HEAD. Useful for spotting inconsistent
        naming and shared inputs.
      </p>
      <PlaceholderIndex rows={specs.placeholders} />
    </ReportSection>

    <ReportFooter specs={specs} />
  </RootBackground>
);

const PromptDetailPage: React.FC<{ specs: ReportSpecs; name: string; onBack: () => void }> = ({
  specs,
  name,
  onBack,
}) => {
  const entry = specs.diffCorpus[name];
  const revs = entry ? Object.keys(entry.revisions) : [];
  const head = entry && revs[0] ? entry.revisions[revs[0]] : null;

  return (
    <RootBackground>
      <DocumentChrome
        source={`promptlm report · ${specs.repo.url}`}
        breadcrumb={['catalog', entry?.group ?? '—', name]}
        detail={`prompts/${entry?.group ?? '—'}/${name}.toml`}
        secondaryLink={
          revs.length >= 2
            ? {
                label: 'open in diff →',
                href: buildDiffHref(name, revs[1], name, revs[0]),
              }
            : undefined
        }
      />

      {!entry || !head ? (
        <div style={{ padding: '64px 56px', color: 'var(--pl-ink-700)' }}>
          <Mono size={12} color="var(--pl-ink-500)">
            No prompt named <span style={{ color: 'var(--pl-ink-800)' }}>{name}</span> in this
            corpus.
          </Mono>
          <div style={{ marginTop: 16 }}>
            <button
              type="button"
              className="pl-btn pl-btn-ghost"
              style={{ height: 32, padding: '0 14px', fontSize: 13 }}
              onClick={onBack}
            >
              ← Back to overview
            </button>
          </div>
        </div>
      ) : (
        <div style={{ padding: '40px 56px 64px' }}>
          <Mono
            size={11}
            color="var(--pl-signal-deep)"
            style={{ letterSpacing: '0.14em', textTransform: 'uppercase', fontWeight: 500 }}
          >
            Prompt
          </Mono>
          <h1
            style={{
              margin: '8px 0 0',
              fontFamily: 'var(--pl-display)',
              fontSize: 40,
              fontWeight: 500,
              letterSpacing: '-0.02em',
              lineHeight: 1.05,
              color: 'var(--pl-ink-900)',
            }}
          >
            {head.spec.name}
          </h1>
          <p
            style={{
              margin: '14px 0 0',
              fontSize: 14.5,
              lineHeight: 1.55,
              color: 'var(--pl-ink-600)',
              maxWidth: 720,
            }}
          >
            <Mono color="var(--pl-ink-700)">v{head.spec.version}</Mono>
            {' · '}revision {head.spec.revision}
            {' · '}
            <Mono color="var(--pl-ink-700)">
              {head.spec.request.vendor}/{head.spec.request.model}
            </Mono>
          </p>
          <div style={{ marginTop: 22 }}>
            <Mono size={11} color="var(--pl-ink-500)" style={{ letterSpacing: '0.10em' }}>
              {revs.length} revisions captured
            </Mono>
          </div>
        </div>
      )}

      <ReportFooter specs={specs} />
    </RootBackground>
  );
};

const DiffPage: React.FC<{
  specs: ReportSpecs;
  initial: DiffSelection;
  onBack: () => void;
}> = ({ specs, initial, onBack }) => {
  const [sel, setSel] = useState<DiffSelection>(initial);
  const A = specs.diffCorpus[sel.promptA]?.revisions[sel.revA];
  const B = specs.diffCorpus[sel.promptB]?.revisions[sel.revB];

  return (
    <RootBackground>
      <DocumentChrome source={`promptlm report · ${specs.repo.url}`} detail="diff" />
      <div style={{ padding: '36px 56px 8px' }}>
        <Mono
          size={11}
          color="var(--pl-signal-deep)"
          style={{
            letterSpacing: '0.14em',
            textTransform: 'uppercase',
            fontWeight: 500,
            display: 'block',
            marginBottom: 10,
          }}
        >
          Diff
        </Mono>
        <h1
          style={{
            margin: 0,
            fontFamily: 'var(--pl-display)',
            fontSize: 36,
            fontWeight: 500,
            letterSpacing: '-0.02em',
            lineHeight: 1.05,
            color: 'var(--pl-ink-900)',
          }}
        >
          Compare two prompts.
          <span style={{ color: 'var(--pl-ink-500)' }}>
            {' '}
            Anywhere in the corpus, any rev.
          </span>
        </h1>
        <p
          style={{
            margin: '12px 0 0',
            fontSize: 14.5,
            lineHeight: 1.55,
            color: 'var(--pl-ink-600)',
            maxWidth: 720,
          }}
        >
          Pick a prompt and a revision on each side. Most-common case: same prompt across two revs.
        </p>
      </div>
      <div style={{ padding: '24px 56px 0' }}>
        <DiffPickerStrip selection={sel} corpus={specs.diffCorpus} onChange={setSel} />
      </div>
      <div style={{ padding: '24px 56px 0' }}>
        <DiffSummary A={A?.spec} B={B?.spec} />
      </div>
      <div style={{ padding: '24px 56px 24px' }}>
        <SpecDiffBody
          A={A?.spec}
          B={B?.spec}
          sourcePath={
            A?.spec
              ? `prompts/${A.spec.group}/${A.spec.name}.toml`
              : undefined
          }
        />
      </div>
      <div style={{ padding: '0 56px 56px' }}>
        <button
          type="button"
          className="pl-btn pl-btn-ghost"
          style={{ height: 32, padding: '0 14px', fontSize: 13 }}
          onClick={onBack}
        >
          ← Back to overview
        </button>
      </div>
      <ReportFooter specs={specs} />
    </RootBackground>
  );
};

export const App: React.FC = () => {
  const specs = useMemo(() => loadSpecs(), []);
  const [route, navigate] = useHashRoute();

  if (route.kind === 'prompt') {
    return (
      <PromptDetailPage specs={specs} name={route.name} onBack={() => navigate('/')} />
    );
  }

  if (route.kind === 'diff') {
    const initial: DiffSelection = {
      promptA: route.promptA ?? specs.defaultDiffSelection.promptA,
      revA: route.revA ?? specs.defaultDiffSelection.revA,
      promptB: route.promptB ?? specs.defaultDiffSelection.promptB,
      revB: route.revB ?? specs.defaultDiffSelection.revB,
    };
    return <DiffPage specs={specs} initial={initial} onBack={() => navigate('/')} />;
  }

  return (
    <OverviewPage
      specs={specs}
      onPromptSelect={(item) => navigate(buildPromptHref(item.name).slice(1))}
      onTimelineDiff={(entry) => {
        const corpusEntry = specs.diffCorpus[entry.prompt];
        if (!corpusEntry) {
          navigate(buildDiffHref().slice(1));
          return;
        }
        const revs = Object.keys(corpusEntry.revisions);
        const newer = revs[0];
        const older = revs[1] ?? newer;
        navigate(buildDiffHref(entry.prompt, older, entry.prompt, newer).slice(1));
      }}
    />
  );
};
